# Generated by Django 4.1.4 on 2022-12-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalizacion'),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion web'),
        ),
    ]
